FROM node:20-alpine

WORKDIR /homecontrol-ui

COPY package.json yarn.lock .yarnrc.yml /homecontrol-ui/
RUN corepack enable
RUN yarn workspaces focus --production

COPY . .

ARG NEXT_PUBLIC_HOMECONTROL_API_URL
ENV NEXT_PUBLIC_HOMECONTROL_API_URL=${NEXT_PUBLIC_HOMECONTROL_API_URL}

RUN yarn build

CMD ["yarn", "start"]